# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_caricadati.ui'
#
# Created: Wed Apr 29 09:39:05 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FloodRisk(object):
    def setupUi(self, FloodRisk):
        FloodRisk.setObjectName(_fromUtf8("FloodRisk"))
        FloodRisk.resize(830, 643)
        self.horizontalLayoutWidget = QtGui.QWidget(FloodRisk)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(530, 610, 269, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.groupBox = QtGui.QGroupBox(FloodRisk)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 811, 131))
        self.groupBox.setMouseTracking(False)
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox {border: 1px solid gray; border-radius: 5px; margin-top: 7px; margin-bottom: 7px; padding: 0px} QGroupBox::title {top:-7 ex;left: 10px; subcontrol-origin: border}\n"
""))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.txtShellFilePath = QtGui.QLineEdit(self.groupBox)
        self.txtShellFilePath.setGeometry(QtCore.QRect(10, 40, 661, 31))
        self.txtShellFilePath.setObjectName(_fromUtf8("txtShellFilePath"))
        self.btnChooseShellFile_1 = QtGui.QPushButton(self.groupBox)
        self.btnChooseShellFile_1.setGeometry(QtCore.QRect(690, 40, 91, 31))
        self.btnChooseShellFile_1.setObjectName(_fromUtf8("btnChooseShellFile_1"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.btnChooseShellFile_3 = QtGui.QPushButton(self.groupBox)
        self.btnChooseShellFile_3.setGeometry(QtCore.QRect(10, 80, 251, 31))
        self.btnChooseShellFile_3.setObjectName(_fromUtf8("btnChooseShellFile_3"))
        self.label_loading = QtGui.QLabel(self.groupBox)
        self.label_loading.setGeometry(QtCore.QRect(310, 70, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_loading.setFont(font)
        self.label_loading.setTextFormat(QtCore.Qt.AutoText)
        self.label_loading.setObjectName(_fromUtf8("label_loading"))
        self.groupBox_2 = QtGui.QGroupBox(FloodRisk)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 811, 71))
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox {border: 1px solid gray; border-radius: 5px; margin-top: 7px; margin-bottom: 7px; padding: 0px} QGroupBox::title {top:-7 ex;left: 10px; subcontrol-origin: border}\n"
""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btnChooseShellFile_2 = QtGui.QPushButton(self.groupBox_2)
        self.btnChooseShellFile_2.setGeometry(QtCore.QRect(10, 20, 201, 28))
        self.btnChooseShellFile_2.setObjectName(_fromUtf8("btnChooseShellFile_2"))
        self.label_sr = QtGui.QLabel(self.groupBox_2)
        self.label_sr.setEnabled(True)
        self.label_sr.setGeometry(QtCore.QRect(230, 30, 541, 16))
        self.label_sr.setObjectName(_fromUtf8("label_sr"))
        self.groupBox_3 = QtGui.QGroupBox(FloodRisk)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 210, 411, 401))
        self.groupBox_3.setStyleSheet(_fromUtf8("QGroupBox {border: 1px solid gray; border-radius: 5px; margin-top: 7px; margin-bottom: 7px; padding: 0px} QGroupBox::title {top:-7 ex;left: 10px; subcontrol-origin: border}\n"
""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btnChooseShellFile_4 = QtGui.QPushButton(self.groupBox_3)
        self.btnChooseShellFile_4.setEnabled(False)
        self.btnChooseShellFile_4.setGeometry(QtCore.QRect(320, 50, 81, 28))
        self.btnChooseShellFile_4.setObjectName(_fromUtf8("btnChooseShellFile_4"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 301, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 301, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btnChooseShellFile_5 = QtGui.QPushButton(self.groupBox_3)
        self.btnChooseShellFile_5.setEnabled(False)
        self.btnChooseShellFile_5.setGeometry(QtCore.QRect(320, 140, 81, 28))
        self.btnChooseShellFile_5.setObjectName(_fromUtf8("btnChooseShellFile_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(40, 220, 301, 18))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btnChooseShellFile_6 = QtGui.QPushButton(self.groupBox_3)
        self.btnChooseShellFile_6.setEnabled(False)
        self.btnChooseShellFile_6.setGeometry(QtCore.QRect(320, 240, 81, 28))
        self.btnChooseShellFile_6.setObjectName(_fromUtf8("btnChooseShellFile_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(40, 270, 301, 18))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.btnChooseShellFile_7 = QtGui.QPushButton(self.groupBox_3)
        self.btnChooseShellFile_7.setEnabled(False)
        self.btnChooseShellFile_7.setGeometry(QtCore.QRect(320, 290, 81, 28))
        self.btnChooseShellFile_7.setObjectName(_fromUtf8("btnChooseShellFile_7"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 140, 70, 17))
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 240, 70, 17))
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 290, 70, 17))
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.btnChooseShellFile_8 = QtGui.QPushButton(self.groupBox_3)
        self.btnChooseShellFile_8.setGeometry(QtCore.QRect(10, 330, 371, 28))
        self.btnChooseShellFile_8.setObjectName(_fromUtf8("btnChooseShellFile_8"))
        self.btnChooseShellFile_9 = QtGui.QPushButton(self.groupBox_3)
        self.btnChooseShellFile_9.setEnabled(False)
        self.btnChooseShellFile_9.setGeometry(QtCore.QRect(320, 190, 81, 28))
        self.btnChooseShellFile_9.setObjectName(_fromUtf8("btnChooseShellFile_9"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(40, 170, 301, 18))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txtShellFilePath_6 = QtGui.QLineEdit(self.groupBox_3)
        self.txtShellFilePath_6.setEnabled(False)
        self.txtShellFilePath_6.setGeometry(QtCore.QRect(40, 190, 271, 26))
        self.txtShellFilePath_6.setObjectName(_fromUtf8("txtShellFilePath_6"))
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QtCore.QRect(40, 50, 271, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 140, 271, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setGeometry(QtCore.QRect(40, 240, 271, 22))
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_5.setEnabled(False)
        self.comboBox_5.setGeometry(QtCore.QRect(40, 290, 271, 21))
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.checkBox_All = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_All.setGeometry(QtCore.QRect(10, 90, 271, 17))
        self.checkBox_All.setObjectName(_fromUtf8("checkBox_All"))
        self.progressBarGeo = QtGui.QProgressBar(self.groupBox_3)
        self.progressBarGeo.setGeometry(QtCore.QRect(10, 360, 371, 23))
        self.progressBarGeo.setProperty("value", 0)
        self.progressBarGeo.setObjectName(_fromUtf8("progressBarGeo"))
        self.groupBox_4 = QtGui.QGroupBox(FloodRisk)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 210, 391, 401))
        self.groupBox_4.setStyleSheet(_fromUtf8("QGroupBox {border: 1px solid gray; border-radius: 5px; margin-top: 7px; margin-bottom: 7px; padding: 0px} QGroupBox::title {top:-7 ex;left: 10px; subcontrol-origin: border}\n"
""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.txtShellFilePath_12 = QtGui.QLineEdit(self.groupBox_4)
        self.txtShellFilePath_12.setEnabled(False)
        self.txtShellFilePath_12.setGeometry(QtCore.QRect(40, 240, 251, 26))
        self.txtShellFilePath_12.setObjectName(_fromUtf8("txtShellFilePath_12"))
        self.btnChooseShellFile_16 = QtGui.QPushButton(self.groupBox_4)
        self.btnChooseShellFile_16.setEnabled(False)
        self.btnChooseShellFile_16.setGeometry(QtCore.QRect(300, 240, 81, 28))
        self.btnChooseShellFile_16.setObjectName(_fromUtf8("btnChooseShellFile_16"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(40, 220, 301, 18))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(40, 270, 301, 18))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.btnChooseShellFile_17 = QtGui.QPushButton(self.groupBox_4)
        self.btnChooseShellFile_17.setEnabled(False)
        self.btnChooseShellFile_17.setGeometry(QtCore.QRect(300, 290, 81, 28))
        self.btnChooseShellFile_17.setObjectName(_fromUtf8("btnChooseShellFile_17"))
        self.txtShellFilePath_13 = QtGui.QLineEdit(self.groupBox_4)
        self.txtShellFilePath_13.setEnabled(False)
        self.txtShellFilePath_13.setGeometry(QtCore.QRect(40, 290, 251, 26))
        self.txtShellFilePath_13.setObjectName(_fromUtf8("txtShellFilePath_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(40, 170, 301, 18))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.btnChooseShellFile_18 = QtGui.QPushButton(self.groupBox_4)
        self.btnChooseShellFile_18.setEnabled(False)
        self.btnChooseShellFile_18.setGeometry(QtCore.QRect(300, 190, 81, 28))
        self.btnChooseShellFile_18.setObjectName(_fromUtf8("btnChooseShellFile_18"))
        self.txtShellFilePath_14 = QtGui.QLineEdit(self.groupBox_4)
        self.txtShellFilePath_14.setEnabled(False)
        self.txtShellFilePath_14.setGeometry(QtCore.QRect(40, 190, 251, 26))
        self.txtShellFilePath_14.setObjectName(_fromUtf8("txtShellFilePath_14"))
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 240, 70, 17))
        self.checkBox_9.setText(_fromUtf8(""))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 290, 70, 17))
        self.checkBox_10.setText(_fromUtf8(""))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 190, 70, 17))
        self.checkBox_11.setText(_fromUtf8(""))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.checkBox_All_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_All_3.setGeometry(QtCore.QRect(10, 40, 261, 17))
        self.checkBox_All_3.setObjectName(_fromUtf8("checkBox_All_3"))
        self.btnChooseShellFile_20 = QtGui.QPushButton(self.groupBox_4)
        self.btnChooseShellFile_20.setGeometry(QtCore.QRect(10, 330, 371, 28))
        self.btnChooseShellFile_20.setObjectName(_fromUtf8("btnChooseShellFile_20"))
        self.btnChooseShellFile_21 = QtGui.QPushButton(self.groupBox_4)
        self.btnChooseShellFile_21.setEnabled(False)
        self.btnChooseShellFile_21.setGeometry(QtCore.QRect(300, 140, 81, 28))
        self.btnChooseShellFile_21.setObjectName(_fromUtf8("btnChooseShellFile_21"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(40, 120, 301, 18))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.txtShellFilePath_16 = QtGui.QLineEdit(self.groupBox_4)
        self.txtShellFilePath_16.setEnabled(False)
        self.txtShellFilePath_16.setGeometry(QtCore.QRect(40, 140, 251, 26))
        self.txtShellFilePath_16.setObjectName(_fromUtf8("txtShellFilePath_16"))
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 140, 70, 17))
        self.checkBox_12.setText(_fromUtf8(""))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 90, 70, 17))
        self.checkBox_13.setText(_fromUtf8(""))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.btnChooseShellFile_22 = QtGui.QPushButton(self.groupBox_4)
        self.btnChooseShellFile_22.setEnabled(False)
        self.btnChooseShellFile_22.setGeometry(QtCore.QRect(300, 90, 81, 28))
        self.btnChooseShellFile_22.setObjectName(_fromUtf8("btnChooseShellFile_22"))
        self.txtShellFilePath_17 = QtGui.QLineEdit(self.groupBox_4)
        self.txtShellFilePath_17.setEnabled(False)
        self.txtShellFilePath_17.setGeometry(QtCore.QRect(40, 90, 251, 26))
        self.txtShellFilePath_17.setObjectName(_fromUtf8("txtShellFilePath_17"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(40, 70, 301, 18))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.progressBarAlfa = QtGui.QProgressBar(self.groupBox_4)
        self.progressBarAlfa.setGeometry(QtCore.QRect(10, 360, 371, 23))
        self.progressBarAlfa.setProperty("value", 0)
        self.progressBarAlfa.setObjectName(_fromUtf8("progressBarAlfa"))

        self.retranslateUi(FloodRisk)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), FloodRisk.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FloodRisk.reject)
        QtCore.QMetaObject.connectSlotsByName(FloodRisk)

    def retranslateUi(self, FloodRisk):
        FloodRisk.setWindowTitle(_translate("FloodRisk", "FloodRisk | Database Manager", None))
        self.groupBox.setTitle(_translate("FloodRisk", "Geodatabase SpatiaLite Configuration ", None))
        self.btnChooseShellFile_1.setText(_translate("FloodRisk", "Browse...", None))
        self.label.setText(_translate("FloodRisk", "Geodatabase Name:", None))
        self.btnChooseShellFile_3.setText(_translate("FloodRisk", "Create New Geodatabase", None))
        self.label_loading.setText(_translate("FloodRisk", "Loading data .....  Wait...", None))
        self.groupBox_2.setTitle(_translate("FloodRisk", "Coordinate Reference System (CRS)", None))
        self.btnChooseShellFile_2.setText(_translate("FloodRisk", " Select SRID", None))
        self.label_sr.setText(_translate("FloodRisk", "Current Coordinate Reference System :", None))
        self.groupBox_3.setTitle(_translate("FloodRisk", "Import input layers", None))
        self.btnChooseShellFile_4.setText(_translate("FloodRisk", "Browse...", None))
        self.label_2.setText(_translate("FloodRisk", "Analysis Area:", None))
        self.label_3.setText(_translate("FloodRisk", "Census Data Layer:", None))
        self.btnChooseShellFile_5.setText(_translate("FloodRisk", "Browse...", None))
        self.label_4.setText(_translate("FloodRisk", "Property Polygon Vector Layer:", None))
        self.btnChooseShellFile_6.setText(_translate("FloodRisk", "Browse...", None))
        self.label_5.setText(_translate("FloodRisk", "Infrastructures Line Vector Layer:", None))
        self.btnChooseShellFile_7.setText(_translate("FloodRisk", "Browse...", None))
        self.btnChooseShellFile_8.setText(_translate("FloodRisk", "Load Selected layers into Geodatabase", None))
        self.btnChooseShellFile_9.setText(_translate("FloodRisk", "Browse...", None))
        self.label_6.setText(_translate("FloodRisk", "Census Data Table:", None))
        self.checkBox_All.setText(_translate("FloodRisk", "Select all data", None))
        self.groupBox_4.setTitle(_translate("FloodRisk", "Import alphanumeric input data", None))
        self.btnChooseShellFile_16.setText(_translate("FloodRisk", "Browse...", None))
        self.label_12.setText(_translate("FloodRisk", "Fatality Rate:", None))
        self.label_13.setText(_translate("FloodRisk", "Flood Severity:", None))
        self.btnChooseShellFile_17.setText(_translate("FloodRisk", "Browse...", None))
        self.label_14.setText(_translate("FloodRisk", "Depth-Damage Curves:", None))
        self.btnChooseShellFile_18.setText(_translate("FloodRisk", "Browse...", None))
        self.checkBox_All_3.setText(_translate("FloodRisk", " Select all data", None))
        self.btnChooseShellFile_20.setText(_translate("FloodRisk", "Load selected tables into Geodatabase:", None))
        self.btnChooseShellFile_21.setText(_translate("FloodRisk", "Browse...", None))
        self.label_16.setText(_translate("FloodRisk", "List of Depth-Damage Curves:", None))
        self.btnChooseShellFile_22.setText(_translate("FloodRisk", "Browse...", None))
        self.label_17.setText(_translate("FloodRisk", "Occupancy Type:", None))

