# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_calcolodanno.ui'
#
# Created: Wed Apr 29 09:58:13 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FloodRisk(object):
    def setupUi(self, FloodRisk):
        FloodRisk.setObjectName(_fromUtf8("FloodRisk"))
        FloodRisk.setEnabled(True)
        FloodRisk.resize(652, 555)
        self.toolButtonEsegui = QtGui.QToolButton(FloodRisk)
        self.toolButtonEsegui.setGeometry(QtCore.QRect(460, 480, 181, 31))
        self.toolButtonEsegui.setObjectName(_fromUtf8("toolButtonEsegui"))
        self.pushButtonSalvaProgetto = QtGui.QPushButton(FloodRisk)
        self.pushButtonSalvaProgetto.setEnabled(True)
        self.pushButtonSalvaProgetto.setGeometry(QtCore.QRect(10, 480, 151, 31))
        self.pushButtonSalvaProgetto.setObjectName(_fromUtf8("pushButtonSalvaProgetto"))
        self.pushButtonLoadLayer = QtGui.QPushButton(FloodRisk)
        self.pushButtonLoadLayer.setGeometry(QtCore.QRect(170, 480, 281, 31))
        self.pushButtonLoadLayer.setObjectName(_fromUtf8("pushButtonLoadLayer"))
        self.horizontalLayoutWidget = QtGui.QWidget(FloodRisk)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 520, 631, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setAlignment(QtCore.Qt.AlignHCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setFormat(_fromUtf8(""))
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.buttonBox = QtGui.QDialogButtonBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.groupBox = QtGui.QGroupBox(FloodRisk)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 631, 181))
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox {border: 1px solid gray; border-radius: 5px; margin-top: 7px; margin-bottom: 7px; padding: 0px} QGroupBox::title {top:-7 ex;left: 10px; subcontrol-origin: border}"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.txtShellFilePath = QtGui.QLineEdit(self.groupBox)
        self.txtShellFilePath.setEnabled(False)
        self.txtShellFilePath.setGeometry(QtCore.QRect(10, 40, 601, 26))
        self.txtShellFilePath.setText(_fromUtf8(""))
        self.txtShellFilePath.setObjectName(_fromUtf8("txtShellFilePath"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 301, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 301, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.txtShellFilePath_2 = QtGui.QLineEdit(self.groupBox)
        self.txtShellFilePath_2.setEnabled(False)
        self.txtShellFilePath_2.setGeometry(QtCore.QRect(10, 90, 601, 26))
        self.txtShellFilePath_2.setObjectName(_fromUtf8("txtShellFilePath_2"))
        self.btnChooseShellFile_3 = QtGui.QPushButton(self.groupBox)
        self.btnChooseShellFile_3.setGeometry(QtCore.QRect(550, 140, 61, 28))
        self.btnChooseShellFile_3.setText(_fromUtf8(""))
        self.btnChooseShellFile_3.setIconSize(QtCore.QSize(30, 25))
        self.btnChooseShellFile_3.setObjectName(_fromUtf8("btnChooseShellFile_3"))
        self.txtShellFilePath_3 = QtGui.QLineEdit(self.groupBox)
        self.txtShellFilePath_3.setGeometry(QtCore.QRect(10, 140, 531, 26))
        self.txtShellFilePath_3.setObjectName(_fromUtf8("txtShellFilePath_3"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 301, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox_2 = QtGui.QGroupBox(FloodRisk)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 631, 71))
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox {border: 1px solid gray; border-radius: 5px; margin-top: 7px; margin-bottom: 7px; padding: 0px} QGroupBox::title {top:-7 ex;left: 10px; subcontrol-origin: border}"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 241, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.comboBoxGrafici = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxGrafici.setGeometry(QtCore.QRect(260, 30, 281, 21))
        self.comboBoxGrafici.setObjectName(_fromUtf8("comboBoxGrafici"))
        self.buttonGrafici = QtGui.QPushButton(self.groupBox_2)
        self.buttonGrafici.setGeometry(QtCore.QRect(550, 30, 61, 28))
        self.buttonGrafici.setText(_fromUtf8(""))
        self.buttonGrafici.setIconSize(QtCore.QSize(30, 25))
        self.buttonGrafici.setObjectName(_fromUtf8("buttonGrafici"))
        self.groupBox_3 = QtGui.QGroupBox(FloodRisk)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 280, 631, 191))
        self.groupBox_3.setStyleSheet(_fromUtf8("QGroupBox {border: 1px solid gray; border-radius: 5px; margin-top: 7px; margin-bottom: 7px; padding: 0px} QGroupBox::title {top:-7 ex;left: 10px; subcontrol-origin: border}"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_green_vuln = QtGui.QLabel(self.groupBox_3)
        self.label_green_vuln.setGeometry(QtCore.QRect(570, 90, 21, 21))
        self.label_green_vuln.setText(_fromUtf8(""))
        self.label_green_vuln.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/asus/Desktop/Progetto Tesi Laurea/green20.png")))
        self.label_green_vuln.setObjectName(_fromUtf8("label_green_vuln"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 301, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButtonView = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonView.setGeometry(QtCore.QRect(480, 140, 61, 31))
        self.pushButtonView.setText(_fromUtf8(""))
        self.pushButtonView.setIconSize(QtCore.QSize(30, 25))
        self.pushButtonView.setObjectName(_fromUtf8("pushButtonView"))
        self.txtShellFilePath_6 = QtGui.QLineEdit(self.groupBox_3)
        self.txtShellFilePath_6.setGeometry(QtCore.QRect(10, 140, 461, 26))
        self.txtShellFilePath_6.setObjectName(_fromUtf8("txtShellFilePath_6"))
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(550, 140, 61, 31))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setIconSize(QtCore.QSize(30, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.txtShellFilePath_vulnerato = QtGui.QLineEdit(self.groupBox_3)
        self.txtShellFilePath_vulnerato.setGeometry(QtCore.QRect(10, 90, 531, 26))
        self.txtShellFilePath_vulnerato.setObjectName(_fromUtf8("txtShellFilePath_vulnerato"))
        self.label_green_danno = QtGui.QLabel(self.groupBox_3)
        self.label_green_danno.setGeometry(QtCore.QRect(570, 40, 21, 21))
        self.label_green_danno.setText(_fromUtf8(""))
        self.label_green_danno.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/asus/Desktop/Progetto Tesi Laurea/green20.png")))
        self.label_green_danno.setObjectName(_fromUtf8("label_green_danno"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 301, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 301, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_red_vuln = QtGui.QLabel(self.groupBox_3)
        self.label_red_vuln.setGeometry(QtCore.QRect(570, 90, 21, 21))
        self.label_red_vuln.setText(_fromUtf8(""))
        self.label_red_vuln.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/asus/Desktop/Progetto Tesi Laurea/red20.png")))
        self.label_red_vuln.setObjectName(_fromUtf8("label_red_vuln"))
        self.txtShellFilePath_5 = QtGui.QLineEdit(self.groupBox_3)
        self.txtShellFilePath_5.setGeometry(QtCore.QRect(10, 40, 531, 26))
        self.txtShellFilePath_5.setObjectName(_fromUtf8("txtShellFilePath_5"))
        self.label_red_danno = QtGui.QLabel(self.groupBox_3)
        self.label_red_danno.setGeometry(QtCore.QRect(570, 40, 21, 21))
        self.label_red_danno.setText(_fromUtf8(""))
        self.label_red_danno.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/asus/Desktop/Progetto Tesi Laurea/red20.png")))
        self.label_red_danno.setObjectName(_fromUtf8("label_red_danno"))

        self.retranslateUi(FloodRisk)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), FloodRisk.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FloodRisk.reject)
        QtCore.QMetaObject.connectSlotsByName(FloodRisk)

    def retranslateUi(self, FloodRisk):
        FloodRisk.setWindowTitle(_translate("FloodRisk", "FloodRisk | Direct Economic Damages", None))
        self.toolButtonEsegui.setText(_translate("FloodRisk", "Run Simulation", None))
        self.pushButtonSalvaProgetto.setText(_translate("FloodRisk", "Save Project", None))
        self.pushButtonLoadLayer.setText(_translate("FloodRisk", "Add all Layers to Map Canvas", None))
        self.groupBox.setTitle(_translate("FloodRisk", "Set Input Data", None))
        self.label.setText(_translate("FloodRisk", "Project (.dmg) File:", None))
        self.label_2.setText(_translate("FloodRisk", "SpatiaLite Geodatabase:", None))
        self.label_3.setText(_translate("FloodRisk", "Water Depth Raster Layer:", None))
        self.groupBox_2.setTitle(_translate("FloodRisk", "Charts", None))
        self.label_14.setText(_translate("FloodRisk", "Set Depth-Damage Curves Type:", None))
        self.groupBox_3.setTitle(_translate("FloodRisk", "Output Data", None))
        self.label_6.setText(_translate("FloodRisk", "Global Summary Table:", None))
        self.label_11.setText(_translate("FloodRisk", "Vulnerability Layer:", None))
        self.label_5.setText(_translate("FloodRisk", "Economic Damage Layer:", None))

